### ISSUE TITLE
Failed to put an edited block

### ISSUE THREAD

**Issue by Bunny7** [ItzDennisz/Enhanced-Items#4]
`[18:29:54 ERROR]: Could not pass event PlayerInteractEvent to EnhancedItems v1.2
.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:306) ~[spigot-1.10.2.jar:git-Spigot-72c2605-251a5b6]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62) ~[spigot-1.10.2.jar:git-Spigot-72c2605-251a5b6]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:502) [spigot-1.10.2.jar:git-Spigot-72c2605-251a5b6]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:487) [spigot-1.10.2.jar:git-Spigot-72c2605-251a5b6]
        at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callPlayerInt
eractEvent(CraftEventFactory.java:231) [spigot-1.10.2.jar:git-Spigot-72c2605-251
a5b6]
        at net.minecraft.server.v1_10_R1.PlayerInteractManager.a(PlayerInteractM
anager.java:496) [spigot-1.10.2.jar:git-Spigot-72c2605-251a5b6]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.jav
a:910) [spigot-1.10.2.jar:git-Spigot-72c2605-251a5b6]
        at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(PacketPlayInUseIt
em.java:37) [spigot-1.10.2.jar:git-Spigot-72c2605-251a5b6]
        at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(PacketPlayInUseIt
em.java:1) [spigot-1.10.2.jar:git-Spigot-72c2605-251a5b6]
        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:
13) [spigot-1.10.2.jar:git-Spigot-72c2605-251a5b6]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [
?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.
10.2.jar:git-Spigot-72c2605-251a5b6]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:
732) [spigot-1.10.2.jar:git-Spigot-72c2605-251a5b6]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:
400) [spigot-1.10.2.jar:git-Spigot-72c2605-251a5b6]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:
668) [spigot-1.10.2.jar:git-Spigot-72c2605-251a5b6]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.jav
a:567) [spigot-1.10.2.jar:git-Spigot-72c2605-251a5b6]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
        at me.ItzDennisz.EnhancedItems.EventListener.onPlayerInteract(EventListe
ner.java:178) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0
_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0
_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_111]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:302) ~[spigot-1.10.2.jar:git-Spigot-72c2605-251a5b6]
        ... 17 more`

The jar version is 1.3.1 and the block is a protection stone, when I put it, that error comes out

**Comment by ItzDennisz** [comment]
So your item is a block, and it happens when you place it?

**Comment by Bunny7** [comment]
what do you mean with modded block? I use ender_stone, but I change the name and de lore.

copy and paste the other items and change some things.

`  protection:
    displayName: "&cprotection"
    lore:
    - " "
    - "&4Attributes:"
    - "&c10 x 10"
    id: 0
    type: ENDER_STONE
    enchantmentColor: "&4"
    hideFlags:
    - HIDE_ATTRIBUTES
    recipes:
      recipe_1:
        top: "D D"
        mid: "C C"
        bot: "   "
        values:
          D: DIAMOND
          C: COAL_BLOCK
      recipe_2:
        top: "   "
        mid: "D D"
        bot: "C C"
        values:
          D: DIAMOND
          C: COAL_BLOCK`

**Comment by ItzDennisz** [comment]
I have found out that this is just an annoying bug and should not affect your item.

**Comment by Bunny7** [comment]
So I just ignore console spam? Because when I break the item, the message still appears and does not stop until I shut down the server. thanks for helping

**Comment by ItzDennisz** [comment]
Yes for now just ignore the console  spam until I have time to upload a patch :P

**Comment by Bunny7** [comment]
Of course, thanks for helping! :D

**Comment by ItzDennisz** [comment]
Since the current codebase is absolute shit i will just completely rewrite the entire plugin

**Comment by Bunny7** [comment]
I will wait for it :)

**Comment by ItzDennisz** [comment]
I have started rewriting the codebase. Everything will be completely different so prepare to rewrite your scripts and items.yml file :P

**Comment by ItzDennisz** [comment]
Oh, also, I will try to make it so that blocks keep their data when placed.

**Comment by Bunny7** [comment]
Do not forget the commands hahahaha

**Comment by ItzDennisz** [comment]
Won't be fixed unless the bug gets reported again after the rewrite.

**Comment by ItzDennisz** [comment]
Definitely not lol. Just started working on 'em!
